### ISSUE TITLE
Admin: "Total submissions" should be "Hand ins" and show x/y

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#21]
where x is number of hand-ins and y is the number og students that have access to the quiz

**Comment by iainbryson** [comment]
Is it acceptable to compute this student list at quiz creation?  Or does it have to be “live” when the admin page is rendered?On Mar 10, 2016, at 6:25 PM, dtu-compute <notifications@github.com> wrote:where x is number of hand-ins and y is the number og students that have access to the quiz—Reply to this email directly or view it on GitHub.

**Comment by dtu-compute** [comment]
That is perfectly fine.

**Comment by iainbryson** [comment]
Another nuance: it seems that it would be more useful to have this as:

X =  the number of students who’ve given handed in at least one submission
Y = total number of students

Otherwise if half the students submitted two quizzes and the other half submitted 0, we’d end up with Y/Y which looks like 100% hand in rate for the student population.  That seems misleading to me.

Thoughts?

**Comment by dtu-compute** [comment]
That could have fun to debug =)

Yes, let's do that =)
