### ISSUE TITLE
begin/end feedback multi line squished into one line

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#217]
On below screenshot is begin/end feedback multi line squished into one line.

The quiz code is at the bottom where I had to insert `xxx` before the set of triple back ticks to prevent Github from thinking the code block ends at the quiz' code blocks.

![bug_answer](https://cloud.githubusercontent.com/assets/13518486/22518453/e959c830-e8ac-11e6-88b0-63a912d2acea.png)

```
begin:multiple_choice
begin:text

The content of the heavy metal Cadmium in canned tuna were measured in tuna from 3 different manufacturers of canned tuna. From each manufacturer 5 cans of tuna were randomly selected. The following quantities of Cadmium in $\mu$g$/$kg were measured in the 15 different cans of tuna:

| Manufacturer 1:| 57 | 52 | 62 | 49 | 43  |
| Manufacturer 2:| 55 | 74 | 62 | 42 | 52  |
| Manufacturer 3:| 61 | 54 | 55 | 53 | 51  |

 What is the 3. quartile (upper) of the Cadmium content at Manufacturer 1? (Using the definition of the eNote)
end:text

	wrong "52"
	wrong "54.5"
	begin:right
		begin:option
			57
		end:option
		begin:feedback
		
			The approach to calculate the third quartile is given in chapter 1. First we have to order the measurements from smallest to largest:
			43, 49, 52, 57, 62. Then we calculate $p \cdot n=0.75 \cdot 5=3.75$, and round it up to 4, and the third quartile is then measurement 4 which is 57.
			
			Note that in *R* it would be solved as:
xxx```R
x=c(57, 52, 62, 49, 43)
quantile(x,type=2)

  0%  25%  50%  75% 100% 
  43   49   52   57   62 
xxx```
			
						
		end:feedback
	end:right
	wrong "52.6"
	wrong "55.75"
	  
end:multiple_choice
```

**Comment by dtu-compute** [comment]
With the latest commit it looks a lot better now.

Now it looks like it puts everything in verbatim, and hence latex and markdown isn't rendered.

![apoagabcjkmohjck](https://cloud.githubusercontent.com/assets/13518486/22589100/c8fccc6a-ea08-11e6-80d5-45edc2c0f2ed.png)

**Comment by iainbryson** [comment]
Yeah, I noticed that when I put in the fix.  The issue is that the if we interpret this as markdown, then:

```
    begin:feedback

     The approach to calculate the third quartile is given in chapter 1. First we have to order the measurements from smallest to largest:
43, 49, 52, 57, 62. Then we calculate $p \cdot n=0.75 \cdot 5=3.75$, and round it up to 4, and the third quartile is then measurement 4 which is 57.

     Note that in *R* it would be solved as:
xxx```R
x=c(57, 52, 62, 49, 43)
quantile(x,type=2)

  0%  25%  50%  75% 100%
  43   49   52   57   62
xxx```
    end:feedback

```

Will get rendered as code because of the indent.  If you then change it to:


```
    begin:feedback

The approach to calculate the third quartile is given in chapter 1. First we have to order the measurements from smallest to largest:
43, 49, 52, 57, 62. Then we calculate $p \cdot n=0.75 \cdot 5=3.75$, and round it up to 4, and the third quartile is then measurement 4 which is 57.

Note that in *R* it would be solved as:
xxx```R
x=c(57, 52, 62, 49, 43)
quantile(x,type=2)

  0%  25%  50%  75% 100%
  43   49   52   57   62
xxx```
    end:feedback

```

We get:



Which seems like what’s expected.

Regards,
— Iain

**Comment by dtu-compute** [comment]
Ok, that makes sense.

Would the solution be to have the quiz parser strip all leading spaces and tabs?

**Comment by iainbryson** [comment]
Possible, but complicated. At a minimum it would mean that the leading spaces in md wouldn’t work;  This is correct syntax after all.  And then we’d have to figure out what to do about fenced code blocks;  Those should clearly not be stripped.  Or maybe just strip out leaving spaces only up until the enclosing begin…

**Comment by dtu-compute** [comment]
It wouldn't be optimal, but as long they can use triple back ticks it would be acceptable for our use. And we don't modify the actual Markdown parser =)

For fenced code blocks, would it be messy to count the number spaces before the first triple back ticks and then extract that number of spaces from each line until the next triple back ticks?

**Comment by iainbryson** [comment]
How about the following:

For the set of lines which contains something other than whitespace, find the minimum number of leading spaces and subtract them from every line.

That way, if everything is indented by N spaces, we remove those.  It seems to be the professors preferred style to indent everything by the same amount, and I think this algorithm would work.

**Comment by dtu-compute** [comment]
Let me see if I understand it correctly. What if the case is this ugly situation?:
<pre>
begin:something
   begin:something
       ```
     A
       B
         C
           D
       ```
   end:something
end:something
</pre>

There are 3 spaces to the nested `begin:something`, 7 spaces in front of the back ticks, and then there is indentation in the code block.

* Would you then run the algorithm twice to also remove the spaces in front of the triple back ticks?
* If, how do you know how many times to run the algorithm?

An error for the A line is probably required I suppose no matter what we do?

**Comment by iainbryson** [comment]
My thought would be to remove only the number of spaces for the
least-indented line (in the example, A). I’m not sure there’s a simpler
solution which won’t yield unexpected results. In particular, either we
ought to have strict indenting rules or none (as it currently is)

As for running the algorithm twice, I don’t recommend doing something
different inside the begin/end based on the specific markdown (e.g. fenced
code block).  So we would only ever run it once, on the whole content
between the :begin and :end.  Doing otherwise willl make things a lot
messier because we’ll need to interpret the Markdown.  I think the most
straightforward implementations would be to strip either the minimum indent
(as described previously) or the indent of the enclosing :begin.

Of course stripping the indent of the enclosing :begin is probably not
exactly what the professors want if they imagine things to be indented
Python-style, since to do that we’d have to know the tab-width also to
determine the ‘expected’ indent of the contents of the block: i.e. we
should really remove :begin + tab-width number of spaces.  Another thing to
consider with that solution is what to do with improper indents — like you
have above.  It’s not clear what’ll be intuitive.  And giving an error for
a block which is Markdown also seems to go against the spirit of Markdown…

So, my recommendation would do the following for your example:

```
begin:something
   begin:something

       ```
     A
       B
         C
           D
       ```
   end:something
end:something

```
->
```

   ```
A
   B
     C
       D
   ```

```

Which wouldn’t render as expected I think, but then it would be relatively
obvious how to fix it.  Maybe not though ;)  As I wrote above, either these
blocks should always have ‘pretty’ indents or we should not care about
indents at all.  Doing different things based on context is going to be
really difficult.


Of course, some of these options prevents some input which could be
considered valid.  e.g. a space-indented code block, where all the lines
were indented by the same number of spaces.  It wouldn’t be possible to
express that if we strip the least-common-denominator space-prefixes…

**Comment by dtu-compute** [comment]
Perfect. let's go with that =)

**Comment by iainbryson** [comment]
Opened https://github.com/dtu-compute/dtu-quiz-parser/issues/12 to track the new parser behavior.
