### ISSUE TITLE
Quiz Q54 failed to load its images from git.

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#229]
For 02323 they want to delete Q54, but get `Quiz Q54 failed to load its images from git.` then they try to change Visible to false.

Clicking View State gives
```
Picture '/assets/quiz-assets/images/02323/53/images/boxplot.png' not found in repo
```
which looks like it haven't updated the image link when closed from Q53 and have somehow mixed the git path with the rails path.

**Comment by iainbryson** [comment]
This is almost certainly the same issue as the cloning bug.  The problem is that the paths and such are stored in the DB and thus persist (though the fix isn’t even ported to 2016 yet).

Regardless, I think we probably want to also not worry about the images when changing visible to false.   Otherwise, as below, you’ll ever be able to delete a quiz.

Do you want to repurpose this issue to be that new behavior?

**Comment by dtu-compute** [comment]
Yes, let's do that.

**Comment by iainbryson** [comment]
This was already fixed.
