### ISSUE TITLE
When handed in a modal should inform about the feedback level

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#71]
When a student have clicked Hand In, a model should appear to let the student know the feedback level.

E.g. if the results will be given at the end date, then the student should be informed when the results will be available.

There are many combinations here, so can you think of a generic way to generate such message?

**Comment by iainbryson** [comment]
This should be straightforward, but maybe I'm misunderstanding because of the "many combinations" comment.

I imagine a dialog which says something like:

You will have access to the following feedback immediately by clicking on the "Results" button for the quiz:

* <bullet list of all feedback types <= feedback_before>

And the following feedback will be given after <end_date>

* <bullet list of feedback types > feedback_before < feedback_after

How does that sound?

**Comment by dtu-compute** [comment]
Great idea! Please do that.
