### ISSUE TITLE
Possible to prevent the admin from clicking multiple times?

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#73]
Is it possible to prevent the admin from clicking multiple times on the same button?

Right now it remembers how many times a button have been clicked.

**Comment by iainbryson** [comment]
What is the problematic behavior being noticed?  I think the most straightforward way to prevent multiple actions being taken is to deselect the quiz when we begin the operation, but I want to make sure that’ll solve the problem.On Apr 12, 2016, at 3:55 PM, dtu-compute <notifications@github.com> wrote:Assigned #73 to @iainbryson.—You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub

**Comment by dtu-compute** [comment]
He clicked many times on Clone because the clone didn't show up right away, so it made several clones, and maybe failed on the last, I am not quite sure about that part.

He mentioned that he would like in (many?) cases that the quiz would remain selected as it would save him from some clicks when writing and testing quizzes. I haven't created a ticket yet, as I expect #53 to solve this request.

This ticket is one of those that would be nice to have fixed, if there is an elegant solution to it, if not, then the admin just have to learn that they should not double click or even click multiple times on buttons.

Could a solution be to insert a delay right after each click before the UI would listen for new clicks?
